import * as z from 'zod'

export const formEditClientCarSchema = z.object({
  id: z.number().int().positive(),

  gosNumber: z.string().optional(),
  brandName: z.string().optional(),
  models: z.string().optional(),
  carBody: z.string().optional(),
  modelYear: z.string().optional(),
  engine: z.string().optional(),
  volume: z.string().optional(),

  // Двигатель и Система выхлопа
  timingChainLong: z.string().optional(),
  timingChainShort: z.string().optional(),
  chainTensioner1: z.string().optional(),
  chainTensioner2: z.string().optional(),
  chainTensioner3: z.string().optional(),
  chainKit: z.string().optional(),

  timingBelt: z.string().optional(),
  timingBeltTensioner: z.string().optional(),
  timingBeltRoller: z.string().optional(),

  pistons: z.string().optional(),
  pistonsRings: z.string().optional(),
  hydrocompensators: z.string().optional(),
  valveIn: z.string().optional(),
  valveEx: z.string().optional(),
  valveGuidesIn: z.string().optional(),
  valveGuidesEx: z.string().optional(),
  bearingConnectingRod: z.string().optional(),
  bearingCamshaft: z.string().optional(),
  crankshaftCamberRings: z.string().optional(),

  generatorBelt: z.string().optional(),
  powerSteeringBelt: z.string().optional(),
  airConditionerBelt: z.string().optional(),
  tensionToller: z.string().optional(),
  bypassRoller1: z.string().optional(),
  bypassRoller2: z.string().optional(),
  generatorOverrunningClutch: z.string().optional(),

  engineGasketKit: z.string().optional(),
  headGasket: z.string().optional(),
  valveCoverGasketLeft: z.string().optional(),
  valveCoverGasketRight: z.string().optional(),
  valveCoverGasket: z.string().optional(),
  intakeManifoldGasket: z.string().optional(),
  exhaustManifoldGasket: z.string().optional(),
  exhaustPipeGasket1: z.string().optional(),
  exhaustPipeGasket2: z.string().optional(),
  exhaustPipeGasket3: z.string().optional(),

  frontLeftEngineCushion: z.string().optional(),
  frontRightEngineCushion: z.string().optional(),
  engineCushionLeft: z.string().optional(),
  engineCushionRear: z.string().optional(),

  frontCrankshaftOilSeal: z.string().optional(),
  rearCrankshaftOilSeal: z.string().optional(),
  camshaftOilSeal: z.string().optional(),
  oilPumpPacking: z.string().optional(),
  intakeOilCaps: z.string().optional(),
  exhaustOilCaps: z.string().optional(),

  airDuctCorrugation: z.string().optional(),

  oilFilter: z.string().optional(),
  airFilter: z.string().optional(),
  fuelFilter: z.string().optional(),
  cabinFilter: z.string().optional(),

  // Подвеска и рулевое управление
  frontLeftShockAbsorber: z.string().optional(),
  frontRightShockAbsorber: z.string().optional(),
  rearLeftShockAbsorber: z.string().optional(),
  rearRightShockAbsorber: z.string().optional(),

  wheelStud: z.string().optional(),
  wheelNut: z.string().optional(),

  leftFrontStrutSupport: z.string().optional(),
  rightFrontStrutSupport: z.string().optional(),
  leftRearStrutSupport: z.string().optional(),
  rightRearStrutSupport: z.string().optional(),
  frontSupportBearing: z.string().optional(),
  frontLeftStrutDuster: z.string().optional(),
  frontRightStrutDuster: z.string().optional(),
  rearLeftStrutDuster: z.string().optional(),
  rearRightStrutDuster: z.string().optional(),
  frontStrutBumper: z.string().optional(),
  rearStrutBumper: z.string().optional(),

  frontLeftHubBearing: z.string().optional(),
  frontRightHubBearing: z.string().optional(),
  rearLeftHubBearing: z.string().optional(),
  rearRightHubBearing: z.string().optional(),

  hydraulicPowerSteeringKit: z.string().optional(),
  railSealsAndGaskets: z.string().optional(),
  steeringRackDustCoverLeft: z.string().optional(),
  steeringRackDustCoverRight: z.string().optional(),

  frontLowerLeftArm: z.string().optional(),
  frontLowerRightArm: z.string().optional(),
  frontUpperLeftArm: z.string().optional(),
  frontUpperRightArm: z.string().optional(),
  rearLeftLongitudinalArm: z.string().optional(),
  rearRightLongitudinalArm: z.string().optional(),
  rearLeftTransverseArm1: z.string().optional(),
  rearRightTransverseArm1: z.string().optional(),
  rearLeftTransverseArm2: z.string().optional(),
  rearRightTransverseArm2: z.string().optional(),
  rearCrescentArm: z.string().optional(),
  rearUpperShortArm: z.string().optional(),

  frontLowerControlArmFrontSilentBlock: z.string().optional(),
  frontLowerControlArmRearSilentBlock: z.string().optional(),
  frontUpperControlArmFrontSilentBlock: z.string().optional(),
  frontUpperControlArmRearSilentBlock: z.string().optional(),
  longitudinalArmSilentBlockLeft: z.string().optional(),
  longitudinalArmSilentBlockRight: z.string().optional(),
  longitudinalHubArmSilentBlockLeft: z.string().optional(),
  bodyLeftCrossArmSilentBlock: z.string().optional(),
  hubLeftCrossArmSilentBlock: z.string().optional(),
  bodyRightCrossArmSilentBlock: z.string().optional(),
  hubRightCrossArmSilentBlock: z.string().optional(),
  camberArmSilentBlock1: z.string().optional(),
  camberArmSilentBlock2: z.string().optional(),
  frontSubframeSilentBlock: z.string().optional(),
  rearSubframeSilentBlock: z.string().optional(),
  frontStabilizerSushings: z.string().optional(),
  frontStabilizerSushingsLeft: z.string().optional(),
  frontStabilizerSushingsRight: z.string().optional(),
  rearStabilizerSushings: z.string().optional(),
  frontLeftStabilizerBar: z.string().optional(),
  frontRightStabilizerBar: z.string().optional(),
  rearLeftStabilizerBar: z.string().optional(),
  rearRightStabilizerBar: z.string().optional(),

  steeringLinkLeft: z.string().optional(),
  steeringLinkRight: z.string().optional(),
  outerLeftSteeringKnuckle: z.string().optional(),
  outerRightSteeringKnuckle: z.string().optional(),
  leftInnerSteeringKnuckle: z.string().optional(),
  leftRightSteeringKnuckle: z.string().optional(),

  lowerLeftBallJoint: z.string().optional(),
  lowerRightBallJoint: z.string().optional(),
  upperLeftBallJoint: z.string().optional(),
  upperRightBallJoint: z.string().optional(),

  // Тормозная система
  frontHandbrakeCable: z.string().optional(),
  rearLeftCable: z.string().optional(),
  reaRightCable: z.string().optional(),

  frontBrakeDiskLeft: z.string().optional(),
  frontBrakeDiskRight: z.string().optional(),
  rearBrakeDisk: z.string().optional(),

  frontBrake: z.string().optional(),
  rearBrake: z.string().optional(),
  handbrakeBrakePads: z.string().optional(),

  brakeMasterCylinder: z.string().optional(),
  slaveBrakeCylinder: z.string().optional(),
  drumBrakeCylinderLeft: z.string().optional(),
  drumBrakeCylinderRight: z.string().optional(),

  setOfFrontGuideRailsWithDustCovers: z.string().optional(),
  setOfRearGuideRailsWithDustCovers: z.string().optional(),
  installationKitForFrontPads: z.string().optional(),
  installationKitForRearPads: z.string().optional(),
  installationKitForHandbrakeBrakePads: z.string().optional(),
  frontCaliperRepairKit: z.string().optional(),
  frontCaliperRepairKitWithPiston: z.string().optional(),
  rearCaliperRepairKit: z.string().optional(),
  rearCaliperRepairKitWithPiston: z.string().optional(),

  frontLeftBrakeHose: z.string().optional(),
  frontRightBrakeHose: z.string().optional(),
  rearLeftBrakeHose: z.string().optional(),
  rearRightBrakeHose: z.string().optional(),

  frontLeftOuterBallJoint: z.string().optional(),
  frontRightOuterBallJoint: z.string().optional(),
  frontLeftInnerBallJoint: z.string().optional(),
  frontRightInnerBallJoint: z.string().optional(),
  frontLeftHandDrive: z.string().optional(),
  frontRightHandDrive: z.string().optional(),
  driveShaft: z.string().optional(),

  rearLeftOuterBallJoint: z.string().optional(),
  rearRightOuterBallJoint: z.string().optional(),
  rearLeftInnerBallJoint: z.string().optional(),
  rearRightInnerBallJoint: z.string().optional(),

  automaticTransmissionOilPanGasket: z.string().optional(),
  automaticTransmissionFilter: z.string().optional(),
  automaticTransmissionFillerGasket: z.string().optional(),
  automaticTransmissionOilPanGasket2: z.string().optional(),
  automaticTransmissionFilter2: z.string().optional(),
  transmissionDrainPlug: z.string().optional(),
  transmissionDrainPlugGasket: z.string().optional(),

  suspensionBearing: z.string().optional(),

  frontPistonRodDusterOuter: z.string().optional(),
  frontPistonRodDusterInnerLeft: z.string().optional(),
  frontPistonRodDusterInnerRight: z.string().optional(),

  rearPistonRodDusterOuter: z.string().optional(),
  rearPistonRodDusterInnerLeft: z.string().optional(),
  rearPistonRodDusterInnerRight: z.string().optional(),

  automaticTransmissionTorqueConverterOilSeal: z.string().optional(),
  gearboxPrimaryShaftOilSeal: z.string().optional(),
  gearboxRockerGland: z.string().optional(),
  leftDriveOilSeal: z.string().optional(),
  rightDriveOilSeal: z.string().optional(),

  clutchDisk: z.string().optional(),
  clutchBasket: z.string().optional(),
  releaseBearing: z.string().optional(),
  clutchKit: z.string().optional(),

  clutchMasterCylinder: z.string().optional(),
  clutchSlaveCylinder: z.string().optional(),

  clutchMasterCylinderKit: z.string().optional(),
  clutchSlaveCylinderRepairKit: z.string().optional(),

  waterPump: z.string().optional(),
  thermostat: z.string().optional(),
  radiator: z.string().optional(),
  heaterRadiator: z.string().optional(),
  airConditionerRadiator: z.string().optional(),
  upperPipe: z.string().optional(),
  lowerPipe: z.string().optional(),
  radiatorCap: z.string().optional(),
  expansionTankCap: z.string().optional(),

  // Электрика и Освещение
  oilSensor: z.string().optional(),
  ventilatorSensor: z.string().optional(),
  dashboardTemperatureSensor: z.string().optional(),
  airConditionerSensor: z.string().optional(),
  reverseSensor: z.string().optional(),
  washerMotor: z.string().optional(),
  handwheelCable: z.string().optional(),

  brakeLightBulbs: z.string().optional(),
  parkingLightBulbsFront: z.string().optional(),
  parkingLightBulbsRear: z.string().optional(),
  sideSignalBulbs: z.string().optional(),
  reverseLightBulbs: z.string().optional(),
  mainHeadlightBulbs: z.string().optional(),
  fogLightBulbs: z.string().optional(),

  sparkPlug: z.string().optional(),
  ignitionCoil: z.string().optional(),
  ignitionWires: z.string().optional(),

  timingCover: z.string().optional(),
  slider: z.string().optional(),

  lambdaProbe1: z.string().optional(),
  lambdaProbe2: z.string().optional(),

  frontAbsSensorLeft: z.string().optional(),
  frontAbsSensorRight: z.string().optional(),
  rearAbsSensorLeft: z.string().optional(),
  rearAbsSensorRight: z.string().optional(),

  // Кузов
  driversWiper: z.string().optional(),
  passengerWiper: z.string().optional(),
  hoodShockAbsorbers: z.string().optional(),
})

export type TFormEditClientCarSchema = z.infer<typeof formEditClientCarSchema>
